name: lint

on:
  push:
  pull_request:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-22.04
    name: Check

    steps:
      - uses: actions/checkout@v4

      - name: Install extra deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libclang-dev \
            libasound2-dev \
            libjack-dev \
            libgtk-3-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libxkbcommon-dev \
            libssl-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: i686-pc-windows-gnu
          components: clippy, rustfmt, rust-src

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ewext -> target
            noita-proxy -> target

      - name: Check ewext formatting
        run: cargo fmt --check
        working-directory: ./ewext

      - name: Check proxy formatting
        run: cargo fmt --check
        working-directory: ./noita-proxy

      - name: Cargo check ewext
        run: cargo +nightly check --target=i686-pc-windows-gnu -Zbuild-std="panic_abort,std"
        working-directory: ./ewext

      - name: Cargo check proxy
        run: cargo check
        working-directory: ./noita-proxy

      - name: Clippy ewext
        run: cargo +nightly clippy --target=i686-pc-windows-gnu -Zbuild-std="panic_abort,std" -- -D warnings
        working-directory: ./ewext

      - name: Clippy proxy
        run: cargo clippy -- -D warnings
        working-directory: ./noita-proxy